### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc.ionic#2]
Complete error message from the browser version:

```
Runtime Error
$ is not defined

ReferenceError: $ is not defined
    at http://localhost:8100/assets/bower/jsxc/example/js/example.js:3:1

Ionic Framework: 2.3.0
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 4.2.6
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.88 Safari/537.36 Vivaldi/1.7.735.46
```

This is probably a result from committing also all bower dependencies and omitting a bower config file. It can be easily be fixed by uninstalling and installing jquery again. It would be good to move from bower to npm as single dependency management tool (this is the plan also for jsxc 4.0).

**Comment by bhumin3i** [comment]
facing the same any one please help me.

**Comment by sualko** [comment]
This project is no longer maintained, but we are working on a slimmer alternative. Please stay tuned.

**Comment by bhumin3i** [comment]
@sualko thanks for reply I'm waiting for alternative solution. thanks man..

**Comment by sualko** [comment]
Are you interested in contributing? Because we are always looking for help.

**Comment by bhumin3i** [comment]
@sualko yeah sure, I'm lucky to work with you guys.

**Comment by sualko** [comment]
Awesome that you want to contribute to JSXC :clap::tada:. I pushed my latest attempt to create a mobile client to [jsxc/jsxc.mobile](https://github.com/jsxc/jsxc.mobile). The basic idea is that we have everything which can be shared between a mobile (cordova) and desktop (electron) version in [jsxc/jsxc-plugin-single-page](https://github.com/jsxc/jsxc-plugin-single-page). I'm currently focused on [finalizing JSXC 4.0](https://www.jsxc.org/blog/2018/09/26/v4.0.0-first-alpha-released.html) and have not much time for the mobile and desktop application. It would be awesome if you could help here with your experience. Maybe you have a better idea to structure those apps. If you need help or anything else, you can also send me an email to klaus@jsxc.org.
