### ISSUE TITLE
error when i try to install

### ISSUE THREAD

**Issue by kosmosby** [jsxc/jsxc.ionic#4]
hi, i'm trying to install the app. Could you help please?
Follow instruction and has this errors in my console:

[npm-debug.log](https://github.com/jsxc/jsxc.ionic/files/1401688/npm-debug.log)
$ npm install
npm ERR! addLocal Could not install /Users/kosmos/Documents/git/jsxc.ionic/node_modules/cordova-plugin-app-event
npm WARN deprecated cordova-plugin-console@1.1.0: This plugin has been deprecated since it is now included in the latest versions of cordova-ios
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path /Users/kosmos/Documents/git/jsxc.ionic/node_modules/cordova-plugin-app-event
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/kosmos/Documents/git/jsxc.ionic/node_modules/cordova-plugin-app-event'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/kosmos/Documents/git/jsxc.ionic/node_modules/cordova-plugin-app-event'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kosmos/Documents/git/jsxc.ionic/npm-debug.log

**Comment by sualko** [comment]
Huhuuu, our first third-party tester. @coyoty should be able to help you.

**Comment by kosmosby** [comment]
something wrong with cordova-plugin-app-event. can't install this.
i use node v6.11.4

**Comment by coyoty** [comment]
I updated the dependencies, it should be ok now. Try to remove the node_modules folder, do a git pull and try npm install after

**Comment by kosmosby** [comment]
thanks.

something run, but i see in the browser this error now:

Error
Close
Runtime Error
$ is not defined
Stack
ReferenceError: $ is not defined
    at http://localhost:8100/assets/jsxc-config.js:12:1
Ionic Framework: 3.7.1
Ionic App Scripts: 3.0.0
Angular Core: 4.4.3
Angular Compiler CLI: 4.4.3
Node: 6.11.4
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by kosmosby** [comment]
resolved

this command helped: sudo bower install --allow-root

**Comment by sualko** [comment]
@kosmosby thanks for the hint.

@coyoty please update the documentation accordingly.
