### ISSUE TITLE
JSXC Is loading

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [jsxc/jsxc.ionic#5]
I tried JSXC from web it is working normally with all its features.
When i configured jsxc ionic on mobile it is stuck on jsxc is loading knowing that bosh url , username and password are correct 100% any help in this please ?

**Comment by sualko** [comment]
This project is work in progress and it's likely that it is replaced by some non-ionic one. But thanks for testing anyway. If you like and send you a message once we are in a beta stage.

**Comment by ahmadhaidarahmad** [comment]
Thank you @sualko  for clarifying that ! do u have an idea when it will be working normally ?

**Comment by sualko** [comment]
I hope for mid this year, but it depends on how busy I am at my regular job.
